# 1st Question

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os
from tqdm import tqdm
from collections import Counter
from scipy.sparse import csr_matrix

In [2]:
corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]


# Finding the list of unique words from the corpus

In [3]:
s=list()
l=list()
for i in corpus:
    l=i.split(" ")
    s.extend(l)
s=sorted(s)
unique=set(s)
unique=sorted(unique)
unique=list(unique)
print(unique)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [4]:
vocab={i:j for j,i in enumerate(unique)}
print(vocab)


{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}


In [5]:
tf=[[0 for i in range(len(unique))]for j in range(len(corpus))]
idf=[[0 for i in range(len(unique))]for j in range(len(corpus))]
tfidf=[[0 for i in range(len(unique))]for j in range(len(corpus))]

In [6]:
for i in range(len(corpus)):
    x=corpus[i]
    words=x.split(" ")
    for j in range(len(unique)):
        x=words.count(unique[j])
        if(x>0):
            tf[i][j]=x/len(words)
        
        

# Finding inverse document frequency of words in every string

In [7]:
import math
for i in range(len(corpus)):
    x=corpus[i]
    words=x.split(" ")
    for j in range(len(unique)):
        count=0
        if(unique[j] in x):
            for k in (corpus):
                if(unique[j] in k):
                    count+=1
        idf[i][j]=math.log((len(corpus)+1)/(count+1))+1
        

# Term Frequency

In [8]:
for i in tf:
    print(i)

[0, 0.2, 0.2, 0.2, 0, 0, 0.2, 0, 0.2]
[0, 0.3333333333333333, 0, 0.16666666666666666, 0, 0.16666666666666666, 0.16666666666666666, 0, 0.16666666666666666]
[0.16666666666666666, 0, 0, 0.16666666666666666, 0.16666666666666666, 0, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666]
[0, 0.2, 0.2, 0.2, 0, 0, 0.2, 0, 0.2]


# Inverse Document Frequency

In [9]:
 for i in idf:
    print(i)

[2.6094379124341005, 1.2231435513142097, 1.5108256237659907, 1.0, 2.6094379124341005, 2.6094379124341005, 1.0, 2.6094379124341005, 1.0]
[2.6094379124341005, 1.2231435513142097, 2.6094379124341005, 1.0, 2.6094379124341005, 1.916290731874155, 1.0, 2.6094379124341005, 1.0]
[1.916290731874155, 2.6094379124341005, 2.6094379124341005, 1.0, 1.916290731874155, 2.6094379124341005, 1.0, 1.916290731874155, 1.0]
[2.6094379124341005, 1.2231435513142097, 1.5108256237659907, 1.0, 2.6094379124341005, 2.6094379124341005, 1.0, 2.6094379124341005, 1.0]


# TF-IDF

In [10]:
for i in range(len(tf)):
    for j in range(len(tf[0])):
        tfidf[i][j]=tf[i][j]*idf[i][j]
        

In [11]:
print(tfidf)

[[0.0, 0.24462871026284194, 0.3021651247531982, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2], [0.0, 0.40771451710473655, 0.0, 0.16666666666666666, 0.0, 0.3193817886456925, 0.16666666666666666, 0.0, 0.16666666666666666], [0.3193817886456925, 0.0, 0.0, 0.16666666666666666, 0.3193817886456925, 0.0, 0.16666666666666666, 0.3193817886456925, 0.16666666666666666], [0.0, 0.24462871026284194, 0.3021651247531982, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2]]


In [12]:
from sklearn.preprocessing import Normalizer
Data_normalizer = Normalizer(norm='l2').fit(tfidf)
output = Data_normalizer.transform(tfidf)


# Normalized TF-IDF

In [13]:
for i in output:
    print(i)

[0.         0.46979139 0.58028582 0.38408524 0.         0.
 0.38408524 0.         0.38408524]
[0.         0.6876236  0.         0.28108867 0.         0.53864762
 0.28108867 0.         0.28108867]
[0.51184851 0.         0.         0.26710379 0.51184851 0.
 0.26710379 0.51184851 0.26710379]
[0.         0.46979139 0.58028582 0.38408524 0.         0.
 0.38408524 0.         0.38408524]


In [14]:
from scipy import sparse
print(sparse.csr_matrix(output))

  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149
  (1, 1)	0.6876235979836937
  (1, 3)	0.2810886740337529
  (1, 5)	0.5386476208856762
  (1, 6)	0.2810886740337529
  (1, 8)	0.2810886740337529
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 8)	0.267103787642168
  (3, 1)	0.4697913855799205
  (3, 2)	0.580285823684436
  (3, 3)	0.3840852409148149
  (3, 6)	0.3840852409148149
  (3, 8)	0.3840852409148149


# TF-IDF using sklearn

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer()
x=vect.fit_transform(corpus)
print(x)

  (0, 8)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045
  (1, 8)	0.281088674033753
  (1, 3)	0.281088674033753
  (1, 6)	0.281088674033753
  (1, 1)	0.6876235979836938
  (1, 5)	0.5386476208856763
  (2, 8)	0.267103787642168
  (2, 3)	0.267103787642168
  (2, 6)	0.267103787642168
  (2, 0)	0.511848512707169
  (2, 7)	0.511848512707169
  (2, 4)	0.511848512707169
  (3, 8)	0.38408524091481483
  (3, 3)	0.38408524091481483
  (3, 6)	0.38408524091481483
  (3, 2)	0.5802858236844359
  (3, 1)	0.46979138557992045


In [16]:
print(x.toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


# 2nd Question

In [17]:
import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)

In [18]:
corpus

['slow moving aimless movie distressed drifting young man',
 'not sure lost flat characters audience nearly half walked',
 'attempting artiness black white clever camera angles movie disappointed became even ridiculous acting poor plot lines almost non existent',
 'little music anything speak',
 'best scene movie gerardo trying find song keeps running head',
 'rest movie lacks art charm meaning emptiness works guess empty',
 'wasted two hours',
 'saw movie today thought good effort good messages kids',
 'bit predictable',
 'loved casting jimmy buffet science teacher',
 'baby owls adorable',
 'movie showed lot florida best made look appealing',
 'songs best muppets hilarious',
 'cool',
 'right case movie delivers everything almost right face',
 'average acting main person low budget clearly see',
 'review long overdue since consider tale two sisters single greatest film ever made',
 'put gem movie terms screenplay cinematography acting post production editing directing aspect film makin

# Finding unique words in corpus

In [19]:
s=list()
l=list()
for i in corpus:
    l=i.split(" ")
    s.extend(l)
s=sorted(s)
unique=set(s)
unique=sorted(unique)
unique=list(unique)
print(unique)

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages', 'ago', 'agree', 'agreed', 'aimless', 'air', 'aired', 'akasha', 'akin', 'alert', 'alexander', 'alike', 'allison', 'allow', 'allowing', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'always', 'amateurish', 'amaze', 'amazed', 'amazing', 'amazingly', 'america', 'american', 'americans', 'among', 'amount', 'amusing', 'amust', 'anatomist', 'angel', 'angela', 'angeles', 'angelina', 'angle', 'angles', 'angry', 'anguish', 'angus

In [20]:
vocab={i:j for j,i in enumerate(unique)}
print(vocab)


{'aailiyah': 0, 'abandoned': 1, 'ability': 2, 'abroad': 3, 'absolutely': 4, 'abstruse': 5, 'abysmal': 6, 'academy': 7, 'accents': 8, 'accessible': 9, 'acclaimed': 10, 'accolades': 11, 'accurate': 12, 'accurately': 13, 'accused': 14, 'achievement': 15, 'achille': 16, 'ackerman': 17, 'act': 18, 'acted': 19, 'acting': 20, 'action': 21, 'actions': 22, 'actor': 23, 'actors': 24, 'actress': 25, 'actresses': 26, 'actually': 27, 'adams': 28, 'adaptation': 29, 'add': 30, 'added': 31, 'addition': 32, 'admins': 33, 'admiration': 34, 'admitted': 35, 'adorable': 36, 'adrift': 37, 'adventure': 38, 'advise': 39, 'aerial': 40, 'aesthetically': 41, 'affected': 42, 'affleck': 43, 'afraid': 44, 'africa': 45, 'afternoon': 46, 'age': 47, 'aged': 48, 'ages': 49, 'ago': 50, 'agree': 51, 'agreed': 52, 'aimless': 53, 'air': 54, 'aired': 55, 'akasha': 56, 'akin': 57, 'alert': 58, 'alexander': 59, 'alike': 60, 'allison': 61, 'allow': 62, 'allowing': 63, 'almost': 64, 'along': 65, 'alongside': 66, 'already': 67, 

In [21]:
idf_word=[0 for i in range(len(unique))]

# Finding IDF of every unique word in the corpus

In [22]:
for i in range(len(unique)):
    count=0
    for k in corpus:
        if(unique[i] in k):
            count=count+1
            continue
    idf_word[i]=math.log((len(corpus)+1)/(count+1))+1

In [23]:
print(idf_word)
idf1=idf_word.copy()

[6.922918004572872, 6.922918004572872, 6.229770824012927, 6.922918004572872, 5.3134800921387715, 6.922918004572872, 6.517452896464707, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.517452896464707, 6.922918004572872, 6.517452896464707, 6.517452896464707, 6.922918004572872, 6.922918004572872, 2.6960842593046923, 6.229770824012927, 3.927185731018881, 5.218169912334447, 6.229770824012927, 4.283860674957613, 4.671626205966376, 5.670155036077504, 6.229770824012927, 5.218169912334447, 6.922918004572872, 6.517452896464707, 5.824305715904762, 6.922918004572872, 6.229770824012927, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.006627272698717, 6.922918004572872, 6.922918004572872, 6.517452896464707, 6.229770824012927, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.517452896464707, 6.517452896464707, 6.922918004572872, 4.214867803470662, 6.229770824012927, 6.229770824012927, 5.824305715904762, 6.517452896464707, 6.9229180

# Words with top 50 idf value

In [24]:
max_idf=list()
maxidf_value=list()
count=0
while(count!=50):
    i=idf1.index(max(idf1))
    print(unique[i],max(idf1))
    max_idf.append(unique[i])
    maxidf_value.append(max(idf1))
    idf1[i]=-1
    count=count+1
    

aailiyah 6.922918004572872
abandoned 6.922918004572872
abroad 6.922918004572872
abstruse 6.922918004572872
academy 6.922918004572872
accents 6.922918004572872
accessible 6.922918004572872
acclaimed 6.922918004572872
accolades 6.922918004572872
accurately 6.922918004572872
achille 6.922918004572872
ackerman 6.922918004572872
adams 6.922918004572872
added 6.922918004572872
admins 6.922918004572872
admiration 6.922918004572872
admitted 6.922918004572872
adrift 6.922918004572872
adventure 6.922918004572872
aesthetically 6.922918004572872
affected 6.922918004572872
affleck 6.922918004572872
afternoon 6.922918004572872
agreed 6.922918004572872
aimless 6.922918004572872
aired 6.922918004572872
akasha 6.922918004572872
alert 6.922918004572872
alike 6.922918004572872
allison 6.922918004572872
allowing 6.922918004572872
alongside 6.922918004572872
amateurish 6.922918004572872
amazed 6.922918004572872
amazingly 6.922918004572872
amusing 6.922918004572872
amust 6.922918004572872
anatomist 6.922918

In [25]:
print(max_idf)

['aailiyah', 'abandoned', 'abroad', 'abstruse', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurately', 'achille', 'ackerman', 'adams', 'added', 'admins', 'admiration', 'admitted', 'adrift', 'adventure', 'aesthetically', 'affected', 'affleck', 'afternoon', 'agreed', 'aimless', 'aired', 'akasha', 'alert', 'alike', 'allison', 'allowing', 'alongside', 'amateurish', 'amazed', 'amazingly', 'amusing', 'amust', 'anatomist', 'angela', 'angelina', 'angry', 'anguish', 'angus', 'animals', 'animated', 'anita', 'anniversary', 'anthony', 'antithesis', 'anyway']


In [26]:
print(maxidf_value)

[6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872]


In [27]:
dic={max_idf[i]:maxidf_value[i]for i in range(len(max_idf))} 
print(dic)

{'aailiyah': 6.922918004572872, 'abandoned': 6.922918004572872, 'abroad': 6.922918004572872, 'abstruse': 6.922918004572872, 'academy': 6.922918004572872, 'accents': 6.922918004572872, 'accessible': 6.922918004572872, 'acclaimed': 6.922918004572872, 'accolades': 6.922918004572872, 'accurately': 6.922918004572872, 'achille': 6.922918004572872, 'ackerman': 6.922918004572872, 'adams': 6.922918004572872, 'added': 6.922918004572872, 'admins': 6.922918004572872, 'admiration': 6.922918004572872, 'admitted': 6.922918004572872, 'adrift': 6.922918004572872, 'adventure': 6.922918004572872, 'aesthetically': 6.922918004572872, 'affected': 6.922918004572872, 'affleck': 6.922918004572872, 'afternoon': 6.922918004572872, 'agreed': 6.922918004572872, 'aimless': 6.922918004572872, 'aired': 6.922918004572872, 'akasha': 6.922918004572872, 'alert': 6.922918004572872, 'alike': 6.922918004572872, 'allison': 6.922918004572872, 'allowing': 6.922918004572872, 'alongside': 6.922918004572872, 'amateurish': 6.92291

In [28]:
tf=[[0 for i in range(len(max_idf))]for j in range(len(corpus))]
idf=[[0 for i in range(len(max_idf))]for j in range(len(corpus))]



# Term frequency 

In [29]:
for i in range(len(corpus)):
    x=corpus[i]
    words=x.split(" ")
    for j in range(len(max_idf)):
        x=words.count(max_idf[j])
        if(x>0):
            tf[i][j]=x/len(words)
        
        

In [30]:
print(tf)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [31]:
print(len(tf))
print(len(tf[0]))

746
50


# IDF

In [32]:
for i in range(len(corpus)):
    x=corpus[i]
    words=x.split(" ")
    m=0
    for j in max_idf:
        if(j in words):
            idf[i][m]=dic.get(j)
        m=m+1
        

In [33]:
for i in idf:
    print(i)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6.922918004572872, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [34]:
print(len(idf))
print(len(idf[0]))

746
50


# TF-IDF

In [35]:
tfidf=[[0 for i in range(len(max_idf))]for j in range(len(corpus))]
for i in range(len(idf)):
    for j in range(len(idf[0])):
        tfidf[i][j]=tf[i][j]*idf[i][j]

In [36]:
for i in tfidf:
    print(i)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.865364750571609, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Sparse Matrix representation of TF-IDF with top 50 features

In [37]:
print(sparse.csr_matrix(tfidf))

  (0, 24)	0.865364750571609
  (19, 43)	0.015769744885131828
  (68, 21)	0.38460655580960396
  (72, 23)	1.3845836009145744
  (74, 25)	0.9889882863675531
  (89, 47)	0.7692131116192079
  (135, 3)	0.009918220636923885
  (135, 9)	0.009918220636923885
  (135, 15)	0.009918220636923885
  (135, 17)	0.009918220636923885
  (135, 29)	0.009918220636923885
  (135, 32)	0.009918220636923885
  (135, 40)	0.009918220636923885
  (176, 39)	0.24724707159188827
  (192, 18)	2.307639334857624
  (193, 20)	0.3009964349814292
  (216, 2)	0.4615278669715248
  (225, 16)	0.7692131116192079
  (227, 14)	1.153819667428812
  (241, 35)	1.730729501143218
  (270, 1)	0.22331993563138297
  (290, 22)	0.865364750571609
  (341, 34)	0.9889882863675531
  (344, 33)	0.865364750571609
  (348, 8)	0.5325321541979132
  (409, 5)	2.307639334857624
  (430, 31)	0.865364750571609
  (457, 36)	1.3845836009145744
  (461, 4)	0.49449414318377655
  (461, 44)	0.49449414318377655
  (465, 30)	0.6293561822338974
  (475, 28)	0.38460655580960396
  (493, 

# L2 NORMALIZATION ON TFIDF

In [38]:
Data_normalizer = Normalizer(norm='l2').fit(tfidf)
output = Data_normalizer.transform(tfidf)

In [39]:
print(output)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
len(output)

746

In [41]:
len(output[0])

50

In [42]:
print(sparse.csr_matrix(output))

  (0, 24)	1.0
  (19, 43)	1.0
  (68, 21)	1.0
  (72, 23)	1.0
  (74, 25)	1.0
  (89, 47)	1.0
  (135, 3)	0.3779644730092272
  (135, 9)	0.3779644730092272
  (135, 15)	0.3779644730092272
  (135, 17)	0.3779644730092272
  (135, 29)	0.3779644730092272
  (135, 32)	0.3779644730092272
  (135, 40)	0.3779644730092272
  (176, 39)	1.0
  (192, 18)	1.0
  (193, 20)	1.0
  (216, 2)	1.0
  (225, 16)	1.0
  (227, 14)	1.0
  (241, 35)	1.0
  (270, 1)	1.0
  (290, 22)	1.0
  (341, 34)	1.0
  (344, 33)	1.0
  (348, 8)	1.0
  (409, 5)	1.0
  (430, 31)	1.0
  (457, 36)	1.0
  (461, 4)	0.7071067811865475
  (461, 44)	0.7071067811865475
  (465, 30)	1.0
  (475, 28)	1.0
  (493, 6)	1.0
  (500, 38)	1.0
  (544, 41)	1.0
  (548, 0)	0.7071067811865475
  (548, 26)	0.7071067811865475
  (608, 12)	1.0
  (612, 10)	1.0
  (620, 37)	0.7071067811865476
  (620, 42)	0.7071067811865476
  (632, 7)	1.0
  (644, 11)	0.5773502691896257
  (644, 45)	0.5773502691896257
  (644, 46)	0.5773502691896257
  (667, 19)	1.0
  (691, 27)	1.0
  (699, 48)	1.0
  (722, 1